on: push

jobs:
    job1:
        runs-on: windows-latest
        steps:
            - name: pythonrank
              uses: actions/checkout@v2
            - name: Set up Python 3.12
              uses: actions/setup-python@v2
              with:
                python-version: 3.12
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Run script
              run: python rank.py